### ISSUE TITLE
node_modules folder (missing dependencies)

### ISSUE THREAD

**Issue by gagichce** [pmcoltrane/MTConnect-Node#1]
Hi @pmcoltrane

I've noticed that you have included a `node_modules` folder in the repo and the `packages.config` seems to be missing some dependencies. Would you accept a Pull Request from me if I fix this up?

**Comment by pmcoltrane** [comment]
I haven't touched this repo in a very long time, and am not sure what state it's in. But a package fix seems minor, so if you submit a PR I'll be happy to pull it. 

Edit: I mean "minor" in the sense of being unlikely to break anything that isn't already broken. I don't want to belittle the importance of fixing missing dependencies.

**Comment by pmcoltrane** [comment]
Merged PR #2
